### ISSUE TITLE
Shouldn't there be a `(1-alpha)` pre-factor for the negatives?

### ISSUE THREAD

**Issue by alexander-soare** [mathiaszinnen/focal_loss_torch#2]
So I believe `fl = torch.where(target == 1, fl * self.alpha, fl)` should be `fl = torch.where(target == 1, fl * self.alpha, fl * (1 - self.alpha))`

From the paper section 3.1

> A common method for addressing class imbalance is to introduce a weighting factor α ∈ [0, 1] for class 1 and 1−α for class −1.

**Comment by edricming** [comment]
I agree with Alex :)

**Comment by mathiaszinnen** [comment]
Sorry for the late reaction. I changed the code accordingly, thanks for bringing it up!
