### ISSUE TITLE
Numerical issues with torch.log(p_t)

### ISSUE THREAD

**Issue by kaipackhaeuser** [mathiaszinnen/focal_loss_torch#3]
I run into numerical issues with the current implementation. This is due to the fact that the logarithm of 0 is not defined. This issue could be solved by adding a small number inside torch.log(), for example in the following way:

```
import numpy as np

eps = np.finfo(float).eps
fl = - 1 * (1 - p_t) ** self.gamma * torch.log(p_t + eps)
```

**Comment by mathiaszinnen** [comment]
Thanks for pointing that out, I fixed the issue using your suggestion!
