### ISSUE TITLE
Plans to add multiclass?

### ISSUE THREAD

**Issue by AngledLuffa** [mathiaszinnen/focal_loss_torch#7]
Hi, I was wondering, do you have any plans to add a multiclass version of this module to pip?  This is one of the few pip installable implementations of focal loss, so it would be very convenient to have multiclass support added.

Thanks!

**Comment by mathiaszinnen** [comment]
Hi, 

thanks for letting me know. I'm not sure when I'll find the time but I'll keep it in mind and let you know.

**Comment by AngledLuffa** [comment]
Thank you!  I am giving it a try right now.
